name: lebwohl-lasher
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - attr=2.5.1
  - blas=2.128
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - cython=3.0.12
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.56.0
  - freetype=2.12.1
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libevent=2.1.12
  - libexpat=2.6.4
  - libfabric=2.0.0
  - libfabric1=2.0.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.28
  - libpmix=5.0.6
  - libpng=1.6.46
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libtiff=4.7.0
  - libudev1=257.2
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mpi=1.0
  - mpi4py=4.0.2
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.61.0
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openblas=0.3.28
  - openjpeg=2.5.3
  - openmpi=5.0.6
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python_abi=3.12
  - pyzmq=26.2.1
  - qhull=2020.2
  - rdma-core=56.0
  - readline=8.2
  - setuptools=72.1.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucc=1.3.0
  - ucx=1.18.0
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstd=1.5.6
